/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setoperations;

import java.awt.Graphics;
import java.awt.geom.Point2D;
import java.io.File;
import static java.lang.Math.cos;
import static java.lang.Math.sin;
import java.util.Random;
import javax.swing.JFileChooser;



/**
 *
 * @author 
 */
public class GUI extends javax.swing.JFrame {
    
    public static File f;
    

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intersect = new javax.swing.JButton();
        pointCountField = new javax.swing.JTextField();
        drawPanel1 = new setoperations.drawPanel();
        intsButton = new javax.swing.JButton();
        pointsButton1 = new javax.swing.JButton();
        union = new javax.swing.JButton();
        diff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        intersect.setText("intersect");
        intersect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intersectActionPerformed(evt);
            }
        });

        pointCountField.setText("10");

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        intsButton.setText("Intersections");
        intsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intsButtonActionPerformed(evt);
            }
        });

        pointsButton1.setText("Points");
        pointsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsButton1ActionPerformed(evt);
            }
        });

        union.setText("union");
        union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unionActionPerformed(evt);
            }
        });

        diff.setText("diff");
        diff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(intersect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(union, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(intsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pointsButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pointCountField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(diff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pointCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(pointsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(union, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intersect, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intersectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intersectActionPerformed
       drawPanel1.polyOut = Algorithms.polyIntersect(drawPanel1.polyA, drawPanel1.polyB);
       drawPanel1.polyOut2.clear();
       drawPanel1.repaint();
    }//GEN-LAST:event_intersectActionPerformed

    private void intsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intsButtonActionPerformed
        drawPanel1.intersec = Algorithms.allIntersections(drawPanel1.polyA,drawPanel1.polyB);
        drawPanel1.polyA = Algorithms.divideAll(drawPanel1.polyA, drawPanel1.intersec);
        drawPanel1.polyB = Algorithms.divideAll(drawPanel1.polyB, drawPanel1.intersec);
        Algorithms.setInside(drawPanel1.polyA, drawPanel1.polyB);
        drawPanel1.repaint();
    }//GEN-LAST:event_intsButtonActionPerformed

    private void pointsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsButton1ActionPerformed
       int npoints = Integer.parseInt(pointCountField.getText());
        drawPanel1.polyA = new Polygon(generateStar(npoints));
        drawPanel1.polyB = new Polygon(generateStar(npoints));
        
        drawPanel1.repaint();
        drawPanel1.polyOut.clear();
        drawPanel1.polyOut2.clear();
        drawPanel1.intersec.clear();
    }//GEN-LAST:event_pointsButton1ActionPerformed

    private void unionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unionActionPerformed
       drawPanel1.polyOut =Algorithms.polyUnion(drawPanel1.polyA, drawPanel1.polyB);
       drawPanel1.polyOut2.clear();
       drawPanel1.repaint();
    }//GEN-LAST:event_unionActionPerformed

    private void diffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffActionPerformed
       drawPanel1.polyOut = Algorithms.polyDiff(drawPanel1.polyA, drawPanel1.polyB);      
       drawPanel1.polyOut2 = Algorithms.polyDiff(drawPanel1.polyB, drawPanel1.polyA);   
       drawPanel1.repaint();
    }//GEN-LAST:event_diffActionPerformed

    public Point2D[] generateStar(int size){
        Point2D [] points;
        points = new Point2D[size];
        Random rnd;
        rnd = new Random();
        for (int i=0;i<size;i++){
            double rand = (2*Math.PI/size)*(-i);
            double x = (cos(rand)/2)*rnd.nextDouble() + 0.5;
            double y = (sin(rand)/2)*rnd.nextDouble() + 0.5;
            points[i] = new Point2D.Double(x,y);
        }
        return points;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diff;
    private setoperations.drawPanel drawPanel1;
    private javax.swing.JButton intersect;
    private javax.swing.JButton intsButton;
    private javax.swing.JTextField pointCountField;
    private javax.swing.JButton pointsButton1;
    private javax.swing.JButton union;
    // End of variables declaration//GEN-END:variables
}
